pipeline:

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt:v0.2.2
    commands:
      - /root/entrypoint.sh
      - sbt clean test release
    when:
      event:
        - push
        - pull_request

  build_docker:
    environment:
      - DOCKER_USERNAME=drt_build_bot
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push

  build_tag:
    environment:
      - DOCKER_USERNAME=drt_build_bot
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag

  deploy-to-kube:
    image: quay.io/ukhomeofficedigital/kd:v0.13.0
    secrets:
      - kube_token_acp_notprod
    environment:
      - IMAGE_URL=docker.digital.homeoffice.gov.uk/drt/drt:$${DRONE_COMMIT_SHA}
    commands:
      - apk update
      - apk add curl
      - bin/deploy.sh
    when:
      event: deployment
