pipeline:

  my-build:
    image: docker:18.03
    environment:
      - DOCKER_HOST=tcp://172.17.0.1:2375
    commands:
      - docker build -t drt-v2 ./server/target/docker/stage
    when:
      branch: master
      event: push
