pipeline:
  drone_s3_cache_pull:
     image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
     drone_s3_cache_mode: "pull"

  build:
    commands:
       - sbt clean test release
    image: hseeberger/scala-sbt
    when:
      event:
        - push
        - pull_request
      branch: 
        - drone        

  drone_s3_cache_push:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
    drone_s3_cache_folders:
      - .ivy2
    drone_s3_cache_mode: "push"
