pipeline:

  build:
    image: massimodanieli/docker-scala-sbtjs:latest
    #image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt --error test docker:stage
    environment:
      - ARTIFACTORY_USERNAME=drt_ci
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push
      brach: 
        - drone
        - drt-acp-pgsql  
  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      event:
        - push

  build_docker:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push
      branch: 
        - drone
        - drt-acp-pgsql
  deploy-to-kube:
    image: quay.io/ukhomeofficedigital/kd:v0.13.0
    secrets:
      - kube_token_acp_notprod
    environment:
      - IMAGE_URL=docker.digital.homeoffice.gov.uk/drt/drt:latest
      - INIT_IMAGE_URL=quay.io/ukhomeofficedigital/docker-aws-cli:latest
    commands:
      - apk update
      - apk add curl
      - bin/deploy.sh
    when:
      event: deployment

  e2e:
    image: cypress/base
    environment:
      - CYPRESS_baseUrl=https://ltn.drt-notprod.homeoffice.gov.uk/v2/ltn/live
    commands:
      - npm install --save-dev cypress
      - $(npm bin)/cypress run
    when:
      event: deployment

  copy-e2e-result:
    image: quay.io/ukhomeofficedigital/docker-aws-cli:latest
    secrets:
      - aws_bucket_name
      - aws_access_key_id
      - aws_secret_access_key
    commands:
      - env
      - aws s3 cp cypress/ s3://$AWS_BUCKET_NAME --recursive
    when:
      event: deployment      
  build_tag:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
            event: tag
