pipeline:
  drone_s3_cache_pull:
     image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
     drone_s3_cache_mode: "pull"

  build:
    image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt clean test docker:stage
    environment:
      - ARTIFACTORY_USERNAME=drt_ci
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push
  
  drone_s3_cache_push:
    image: quay.io/ukhomeofficedigital/drone-s3cache:v0.1.0
    drone_s3_cache_folders:
      - .ivy2
    drone_s3_cache_mode: "push"

  build_docker:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt-dev
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push

  build_tag:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt-dev
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag

  deploy-to-kube:
    image: quay.io/ukhomeofficedigital/kd:v0.13.0
    secrets:
      - kube_token_acp_notprod
    environment:
      - IMAGE_URL=docker.digital.homeoffice.gov.uk/drt/drt-dev:$${DRONE_COMMIT_SHA}
    commands:
      - apk update
      - apk add curl
      - bin/deploy.sh
    when:
      event: deployment
