pipeline:

  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      event:
        - push
      branch:
        - master  
  build:
    image: quay.io/ukhomeofficedigital/scala-sbt-nodejs
    commands:
      - /root/entrypoint.sh
      - sbt --error test docker:stage
    environment:
      - ARTIFACTORY_USERNAME=drt_ci
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push
      branch:
        - master


  build_docker:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_BUILD_NUMBER}
      - latest
    when:
      event: push
      branch:
        - master

  cypress-E2E-test:
    image: docker:18.06
    environment:
      - DOCKER_USERNAME=drt_ci
      - DOCKER_HOST=tcp://172.17.0.1:2375
    secrets:
      - docker_password
      - play
    commands:
      - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD} docker.digital.homeoffice.gov.uk
      - docker run  -d --name $${DRONE_COMMIT_SHA} -e KEY_CLOAK_URL="https://sso-dev.notprod.homeoffice.gov.uk/auth/admin/realms/drt-notprod" -e PERSISTENCE_BASE_DIR="/tmp/test" -e PORT_ACCESS_RESTRICTIONS=true -e PORT_CODE="test" -e DQ_S3_BUCKET="" -e ENV="test" docker.digital.homeoffice.gov.uk/drt/drt:latest $${PLAY}
      - docker build -t drt-cypress -f cy-drt-dockfile .
      - docker run  --net=container:$${DRONE_COMMIT_SHA} -e CYPRESS_baseUrl="http://localhost:9000" drt-cypress /bin/bash -c "./node_modules/.bin/cypress run"

    when:
      event: push
      branch: master


  copy-e2e-result:
    image: plugins/s3
    bucket: ${AWS_BUCKET_NAME}
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    source: cypress-result/*
    target: /e2e/
    when:
      event: push
      status: failure

  git_tag:
    image: alpine/git
    secrets: [ ssh_key ]
    commands: 
      - mkdir /root/.ssh/ && echo "$SSH_KEY" > /root/.ssh/id_rsa && chmod 0600 /root/.ssh/id_rsa
      - printf  "host github.com\n HostName github.com\n IdentityFile /root/.ssh/id_rsa\n" > /root/.ssh/config
      - chmod 0600 /root/.ssh/config
      - echo /root/.ssh/config  
      - ls /etc/ssh  
      - git remote add tag-origin  git@github.com:UKHomeOffice/drt-v2.git
      - git tag ${DRONE_BUILD_NUMBER}
      - git push tag-origin ${DRONE_BUILD_NUMBER}
    when:
      event: push      

  deploy_test_port:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - drone_token
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-drt
    deploy_to: acp-notprod
    drone_token: $${DRONE_TOKEN}}
    params: "IMAGE_URL=docker.digital.homeoffice.gov.uk/drt/drt:${DRONE_BUILD_NUMBER},KUBE_NAMESPACE=drt-dev,PORT_CODE=test"     
    when:
      branch: master


  deploy_test_port2:
    image: quay.io/ukhomeofficedigital/drone-trigger:latest
    secrets:
      - drone_token
    drone_server: https://drone.acp.homeoffice.gov.uk
    repo: UKHomeOffice/kube-drt
    deploy_to: acp-notprod
    drone_token: $${DRONE_TOKEN}}
    params: "IMAGE_URL=docker.digital.homeoffice.gov.uk/drt/drt:${DRONE_BUILD_NUMBER},KUBE_NAMESPACE=drt-dev,PORT_CODE=test2"
    when:
      branch: master


  slack_notifiction:
    image: plugins/slack
    webhook: https://hooks.slack.com/services/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
    channel: devs
    username: drone
    template: >
     {{#success build.status}}
        build {{build.number}} succeeded. Good job.
        https://drone.acp.homeoffice.gov.uk/UKHomeOffice/drt-v2/{{build.number}}
      {{else}}
        build {{build.number}} failed. Fix me please.
        https://drone.acp.homeoffice.gov.uk/UKHomeOffice/drt-v2/{{build.number}}
      {{/success}}
    when:
      status: [ success, failure ]
      branch: master 

