pipeline:

  build:
    image: massimodanieli/docker-scala-sbtjs:latest
    #image: quay.io/ukhomeofficedigital/scala-sbt:latest
    commands:
      - /root/entrypoint.sh
      - sbt --error test docker:stage
    environment:
      - ARTIFACTORY_USERNAME=drt_ci
    secrets:
      - ARTIFACTORY_PASSWORD
    when:
      event:
        - push
      brach: 
        - drone
        - drt-acp-pgsql  
  sonar-scanner:
    image: quay.io/ukhomeofficedigital/sonar-scanner:v3.0.1
    when:
      event:
        - push

  build_docker:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_COMMIT_SHA}
      - latest
    when:
      event: push
      branch: 
        - drt-acp-pgsql

  run-for-test:
    image: docker.digital.homeoffice.gov.uk/drt/drt:latest
    commands:
      - export KEY_CLOAK_URL=https://sso-dev.notprod.homeoffice.gov.uk/auth/admin/realms/drt-notprod  
      - export PERSISTENCE_BASE_DIR=/var/lib/drt-v2/live/test
      - export PORT_CODE=test
      - export DQ_S3_BUCKET=""
      - export ENV=test
      - export POSTGRES_PASSWORD=test_password
      - export POSTGRES_HOST=tcp://database:5432
      - export POSTGRES_USER=test_user  
      - bin/drt -Duser.timezone=UTC 
    when:
      event: push

  e2e:
    image: cypress/base
    environment:
            - CYPRESS_baseUrl=https://localhost:9000
    commands:
      - npm install --save-dev cypress
      - $(npm bin)/cypress run
    when:
      event: push

  copy-e2e-result:
    image: plugins/s3
    bucket: ${AWS_BUCKET_NAME}
    access_key: ${AWS_ACCESS_KEY_ID}
    secret_key: ${AWS_SECRET_ACCESS_KEY}
    source: cypress/*
    target: /e2e/   
    when:
      event: push      

  build_tag:
    environment:
      - DOCKER_USERNAME=drt_ci
    image: quay.io/ukhomeofficedigital/drone-docker
    registry: docker.digital.homeoffice.gov.uk
    repo: docker.digital.homeoffice.gov.uk/drt/drt
    secrets: [ docker_password ]
    tags:
      - ${DRONE_TAG}
    when:
      event: tag

  services:
    database:
      image: postgres
      environment:
        - POSTGRES_USER=test_user
        - POSTGRES_DB=test
        - POSTGRES_PASSWORD=test_password  
