---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .NAME }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: {{ .NAME }}
        service: drt-lhr
    spec:
      imagePullSecrets:
        - name: docker-registry-key
      containers:
        - name: drt-dev
          image: {{ .IMAGE_URL }}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
          ports:
            - containerPort: 9012
          env:
            - name: MYSUPERSECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .NAME }}-secret
                  key: mysupersecret
